stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    params:
      - data_ingestion.test_size  
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw
    outs:
      - data/processed

  feature_engineering:
    cmd: python src/feat_engg.py
    deps:
      - src/feat_engg.py
      - data/processed
    params:
      - feature_engineering.max_features  
    outs:
      - data/features

  model_building:
    cmd: python src/model_building.py
    deps:
      - src/model_building.py
      - data/features
    params:
      - model_building.n_estimators 
      - model_building.learning_rate 
    outs:
      - sentiment_model.joblib 

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
      - sentiment_model.joblib
      - data/features
    outs:
      - metrics.json    

